### ISSUE TITLE
ResultListContributor : y a-t-il un moyen pour que la methode getMoreData déclenche un événement dans le collaborativeSearch?

### ISSUE THREAD

**Issue by omarghader** [gisaia/ARLAS-web-core#34]
**Environnement : ReactJS**

Besoin : Je souhaite populer ( et mettre à jour) une liste avec les données du ResultListContributor.

Pour l'instant, je recevais les données du ResultListContributor via la fonction suivante : 

```js
    this.query.bus.contribFilterBus
      .filter(contributor => contributor.identifier === 'resultListContributor')
      .subscribe((contributor) => {
         update(contributor.data);
      });
```

Toutefois, en appelant la fonction getMoreData, la fonction ci-dessus ne reçoit aucun événement.

Sachant qu'en React, nous pouvons pas faire de watch sur la variable **ResultListContributor.data**  et que le getMoreData fait un appel asynchrone pour récupérer les nouvelles données.
Existe-t-il une fonction ( ou un autre moyen ) pour recevoir un événement à la réception des nouvelles données?

**Comment by mbarbet** [comment]
This feature will be implemented in the next version of ARLAS-web-contributors project.  I open an issue in this project.
